### ISSUE TITLE
Criar nova tabela e rotas de instituições

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/doar-computadores-backend#2]
Teremos agora uma base de dados das instituições.

As instituições serão validadas pelo administrador, então elas começam `validated=null`, e quando se tornarem `validated=true` (outra issue) estarão aprovadas, `validated=false` estarão rejeitadas.

- [x] Campos necessários: `id` (auto incremental), `name`, `email`, `phone`, `zip`, `city`, `state`, `streetAddress`, `number`, `complement`, `neighborhood`, `description` (text), `urlInstagram`, `urlLinkedin`, `urlFacebook`, `urlSite`, `type`, `validated`(bool)

- [x] Type poderá ser `recycling` (empresas/instituições que fazem reciclagem de eletronicos), `socialEdTech`(projeto social ligado a educação ou tecnologia), `socialOther` (outros tipos de projetos sociais)

- [x] Receber POST em `/institution`, para criar o registro da instituição, `validated` (não deve ser aceito por post), inicialmente ficará com valor null no banco
- [x] Criar rota GET em `/institution` que retorna a lista de instituições (sem retornar o endereço de email)

**Comment by mazzillio** [comment]
Realizei as tarefas e deixei o script de criação da tabela espero retorno para caso seja necessário fazer uma alteração!
