### ISSUE TITLE
Ativar husky

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/doar-computadores-backend#9]
Esta issue depende do PR #18 ser mergeado.

Queremos permitir que o commit só aconteça se o código estiver de acordo com o eslint e prettier. 
Vamos utilizar o husky local que valida o código rodando as verificações.

- [x] Instalar Husky
- [x] Executar `yarn run checks` antes do commit, que se falhar não acontece o commit

**Comment by BrunoTAlcantara** [comment]
Husk Adcionado
